# Generated by Django 5.0.2 on 2024-02-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassi', models.CharField(max_length=16)),
                ('modelo', models.CharField(max_length=20)),
                ('ano', models.IntegerField(max_length=4)),
                ('placa', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'veiculos',
            },
        ),
    ]
