# Generated by Django 5.0.2 on 2024-02-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculos',
            name='ano',
            field=models.DateField(auto_now_add=True),
        ),
    ]
