# Generated by Django 5.0.2 on 2024-02-19 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_workshop', '0002_alter_veiculos_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculos',
            name='ano',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
