# Generated by Django 5.0.2 on 2024-02-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_workshop', '0004_alter_veiculos_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculos',
            name='chassi',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='veiculos',
            name='placa',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
